In [4]:
!pip install pandas 
!pip install xlrd
!pip install scikit-learn

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.12/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: xlrd in /opt/anaconda3/lib/python3.12/site-packages (2.0.1)
Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.12/site-packages (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn) (2.2.0)

In [62]:
import pandas as pd 
df = pd.read_excel("/Users/levmanulak/Desktop/ПОДКАСТ/data2.xls")

In [70]:
df2 = df.iloc[:-1, :5]

      sepal_length sepal_width petal_length  petal_width          species
0             5.93        3.66         4.94         2.69  Iris-versicolor
1             6.89        3.79         6.16         2.81   Iris-virginica
2             6.70        3.64         5.99         2.81   Iris-virginica
3             6.74        2.68         4.71         2.29  Iris-versicolor
4             5.96        4.16         2.99         1.56      Iris-setosa
...            ...         ...          ...          ...              ...
2418          5.51        3.78         1.46         0.20      Iris-setosa
2419          6.96        3.76         2.73         0.65      Iris-setosa
2420          7.43        4.14         6.11         3.00   Iris-virginica
2421          6.54        4.56         1.69         0.87      Iris-setosa
2422          7.11        4.66          5.3         3.80   Iris-virginica

[2423 rows x 5 columns]

In [238]:
df_sorted = df2.iloc[:1001, :4]

# додав цю команду знизу, бо вибивало помилку, але не повністю розумію, що вона робить

pd.set_option('future.no_silent_downcasting', True)

df3 = df_sorted.fillna(df_sorted.mean())

In [114]:
df_sorted2 = df2.iloc[1001:2001, :4] 

df_sorted2.ffill(inplace=True)

In [122]:
df_sorted3 = df2.iloc[2001:, :4] 

df_sorted3.bfill(inplace=True)

In [222]:
combined_df = pd.concat([df3, df_sorted2, df_sorted3])

#коли туту прописую combined_df.describe(), то мені показує лише дві колонки. 
#але коли просто роблю combined_df, то все окей. чому так?

      sepal_length sepal_width petal_length  petal_width
0             5.93        3.66         4.94         2.69
1             6.89        3.79         6.16         2.81
2             6.70        3.64         5.99         2.81
3             6.74        2.68         4.71         2.29
4             5.96        4.16         2.99         1.56
...            ...         ...          ...          ...
2418          5.51        3.78         1.46         0.20
2419          6.96        3.76         2.73         0.65
2420          7.43        4.14         6.11         3.00
2421          6.54        4.56         1.69         0.87
2422          7.11        4.66          5.3         3.80

[2423 rows x 4 columns]

In [182]:
import sklearn

X = combined_df[['sepal_length', 'sepal_width', 'petal_length']]
Y = combined_df['petal_width']

In [214]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [206]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [234]:
lr.fit(X_train, Y_train)

# тут видає ось таку помилку: could not convert string to float: 'Random'
#не до кінця розумію, чому.

ValueError: could not convert string to float: 'Random'

In [ ]:
lr.predict(X_test)
pred = lr.predict(X_test)
pred